[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'prague'
remappings = [
  "forge-std/=lib/forge-std/src",
  "solady/=lib/solady/",
  "openzeppelin/=lib/openzeppelin-contracts/contracts",
]
via_ir = true
optimizer = true
optimizer_runs = 200
gas_limit = "18446744073709551615"
gas_reports = ["*"]
memory_limit = 134217728
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
